name: pull_request
run-name: ${{ github.actor }} is creating a pull request
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://styled-todo-server.vercel.app'
          method: 'POST'
          data: '{"author": "${{github.actor}}", "from_branch": "${{github.from_branch}}", "to_branch": "${{github.to_branch}}", "createdAt": "${{github.event.repository.updated_at}}"}'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v